name: cicada_build

on:
  push:
    paths:
      - '.github/workflows/cicada_build.yml'
      - 'cicada/**'
      - 'common/**'
      - 'include/**'
      - 'third_party/**'
  pull_request:
    paths:
      - '.github/workflows/cicada_build.yml'
      - 'cicada/**'
      - 'common/**'
      - 'include/**'

jobs:
  Build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - id: Begin
        name: Begin
        run: |
          echo "Begin ${GITHUB_WORKFLOW}/${GITHUB_JOB}"

      - id: Checkout
        name: Checkout
        uses: actions/checkout@v2

      - id: Install_apt
        name: Install_apt
        run: |
          sudo apt update -y
          sudo apt-get install -y $(cat build_tools/ubuntu.deps)

      - id: Submodule_init_recursive
        name: Submodule_init_recursive
        run: |
          git submodule update --init --recursive

      - id: Build_third_party_masstree
        name: Build_third_party_masstree
        run: |
          ./build_tools/bootstrap.sh

      - id: Build_third_party_mimalloc
        name: Build_third_party_mimalloc
        run: |
          ./build_tools/bootstrap_mimalloc.sh

      - id: Build_third_party_googletest
        name: Build_third_party_googletest
        run: |
          ./build_tools/bootstrap_googletest.sh

      - id: Build_cicada
        name: Build_cicada
        run: |
          cd cicada
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug ..
          cmake --build . --target all --clean-first -- -j
