name: tpcc_silo_build_and_ctest

on:
  push:
    paths:
      - '.github/workflows/tpcc_silo_build_and_ctest.yml'
      - 'common/**'
      - 'index/masstree_beta/masstree_beta_wrapper.cpp'
      - 'tpcc_silo/**'
      - 'third_party/**'
  pull_request:
    paths:
      - '.github/workflows/tpcc_silo_build_and_ctest.yml'
      - 'common/**'
      - 'index/masstree_beta/masstree_beta_wrapper.cpp'
      - 'tpcc_silo/**'

jobs:
  Build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - id: Begin
        name: Begin
        run: |
          echo "Begin ${GITHUB_WORKFLOW}/${GITHUB_JOB}"

      - id: Checkout
        name: Checkout
        uses: actions/checkout@v2

      - id: Install_apt
        name: Install_apt
        run: |
          sudo apt update -y
          sudo apt-get install -y $(cat build_tools/ubuntu.deps)

      - id: Submodule_init_recursive
        name: Submodule_init_recursive
        run: |
          git submodule update --init --recursive

      - id: Build_third_party_masstree
        name: Build_third_party_masstree
        run: |
            ./build_tools/bootstrap.sh

      - id: Build_third_party_mimalloc
        name: Build_third_party_mimalloc
        run: |
            ./build_tools/bootstrap_mimalloc.sh

      - id: Build_third_party_googletest
        name: Build_third_party_googletest
        run: |
            ./build_tools/bootstrap_googletest.sh

      - id: Build_tpcc_silo
        name: Build_tpcc_silo
        run: |
          cd tpcc_silo
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug ..
          make -j

      - id: Ctest_tpcc_silo
        name: Ctest_tpcc_silo
        continue-on-error: false
        env:
          GTEST_OUTPUT: xml
          ASAN_OPTIONS: detect_stack_use_after_return=true
        run: |
          cd tpcc_silo
          cd build
          ctest --verbose --timeout 100 -j 100
